spring.application.name=PumpShopBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/pumpshop_db_demo
spring.datasource.username=postgres
spring.datasource.password=221205

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=pumpshop-super-secret-key-must-be-at-least-256-bits-long-for-hmac-sha
jwt.expiration-ms=86400000